debug = false
listen = "${HOME}/.ssh/ssh-agent-multiplexer/agent.sock"
add_targets = [
    "${SSH_AUTH_SOCK}",
]
targets = [
    "${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock",
    "${HOME}/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock",
    "${HOME}/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
]
select_target_command = "/opt/homebrew/bin/ssh-agent-mux-select"
