module_separator = " "
reset_color = false

[bookmarks]
search_depth = 100
exclude = []

[[module]]
type = "Symbol"
symbol = "jj󱗆"
color = "Magenta"

[[module]]
type = "Bookmarks"
separator = ""
color = "Magenta"
behind_symbol = "⇡"
surround_with_quotes = true
ignore_empty_commits = "None"

[[module]]
type = "Commit"
previous_message_symbol = "⇣"
max_length = 24
show_previous_if_empty = false
empty_text = "(no description set)"
surround_with_quotes = true

[module.non_unique]
color = "Black"

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(CONFLICT)"
color = "Red"

[module.divergent]
disabled = false
text = "(DIVERGENT)"
color = "Cyan"

[module.empty]
disabled = false
text = "(EMPTY)"
color = "Yellow"

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color = "Yellow"

[module.hidden]
disabled = false
text = "(HIDDEN)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed} {added}{removed}]"
hide_if_empty = false
color = "Magenta"

[module.changed_files]
prefix = ""
suffix = ""
color = "Cyan"

[module.added_lines]
prefix = "+"
suffix = ""
color = "Green"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "Red"

